export enum AuditAction {
    ORDER_CREATED = 'ORDER_CREATED',
    ORDER_CANCELLED = 'ORDER_CANCELLED',
    TRACKING_SYNC = 'TRACKING_SYNC',
    TOKEN_REFRESH = 'TOKEN_REFRESH',
    RETRY = 'RETRY',
    QUEUE_PROCESSED = 'QUEUE_PROCESSED',
}